### PR TITLE
fix: include shebang in output

### LINKED ISSUE #85: Migrate shebang fix from the Deno repo to here
https://github.com/denoland/deno/pull/17113/files

### PR DESCRIPTION
**Pull request by dsherret**
Closes #85

### CODE REVIEW

File: rs-lib/src/emit.rs [hunk 1]
```diff
@@ -292,3 +306,72 @@ fn transpile_module(
...
+      vec![root.clone()],
+      &mut memory_loader,
+      GraphOptions {
+        module_analyzer: Some(&analyzer),
+        ..Default::default()
+      },
+    )
+    .await;
+    (graph, analyzer, root)
+  }
```
Comment (dsherret) [inline rs-lib/src/emit.rs:354]: I lifted this from deno_doc.

**Review by bartlomieju — APPROVED** [review]
LGTM
